{
 "title": "Multiple Server Overview",
 "description": "Detailed overview with alerts for a single SPP-Server",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "SPP_Server", "label": "Repeat Row for ", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "$SPP_Server Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "SPP_Server" },
  {
   "title": "Server CPU Usage",
   "type": "gauge",
   "description": "95% Percentille over last 24h ",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "cpuram",
     "query": "SELECT percentile(\"cpuUtil\", 90) FROM \"rp_days_14\".\"cpuram\" WHERE $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server RAM Usage",
   "type": "gauge",
   "description": "95% Percentille over last 24h ",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Catalog Space",
   "type": "bargauge",
   "description": "95% Percentille / last 24h of each component memory usage\nMax root storage usage  / last 24h of Server and vSnap",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "percentUsed" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "\"$tag_Mounted\" on $tag_ssh_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "Mounted" ], "type": "tag" },
      { "params": [ "ssh_type" ], "type": "tag" }
     ],
     "measurement": "df_ssh",
     "select": [
      [
       { "params": [ "Use%" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" },
      { "condition": "OR", "key": "ssh_type", "operator": "=", "value": "VSNAP" }
     ]
    }
   ]
  },
  {
   "title": "Housekeeping-Job Durations",
   "type": "stat",
   "description": "Duration of the last execution of selected jobs",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Storage Server Inventory" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "CPU / RAM SPP-Server (REST)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Last Hypervisor Inventory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "Last Catalog Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/.*catalog.*/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "COMPLETED" },
      { "condition": "AND", "key": "subPolicyType", "operator": "=", "value": "BACKUP" }
     ]
    }
   ]
  },
  {
   "title": "Last Storage Server Inventory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Storage Server Inventory" }
     ]
    }
   ]
  },
  {
   "title": "Highest CPU load by Component",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ssh_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT max(\"%idle\") *-1 + 100 FROM \"ssh_mpstat_cmd\" WHERE $timeFilter GROUP BY time(10m), \"COMMAND\"",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM Statistics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Protected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountProtected" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprotected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountUnprotected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPPmon Collection Errors (24h)",
   "type": "gauge",
   "description": "This panel shows how much the dela did increase, leaving out going down again.\nGood for noticing errors, even if they disappeared",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "--constant",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM $SPP_Server.\"rp_days_14\".\"sppmon_metrics\" WHERE $timeFilter AND (\"constant\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--hourly",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM $SPP_Server.rp_days_14.\"sppmon_metrics\" WHERE $timeFilter AND (\"hourly\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--daily",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM $SPP_Server.rp_days_14.\"sppmon_metrics\" WHERE $timeFilter AND (\"daily\" = 'True'))  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--all",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM $SPP_Server.rp_days_14.\"sppmon_metrics\" WHERE  $timeFilter AND (\"all\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Catalog Backup Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Catalog Backup",
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/.*catalog.*/" }
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes CPU Usage ",
   "type": "bargauge",
   "description": "95% percentille of last 24h per Commandgroup",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" }
     ],
     "measurement": "processStats",
     "query": "SELECT PERCENTILE( *, 90) FROM (SELECT sum(\"%CPU\") FROM \"$SPP_Server\".\"rp_days_14\".\"processStats\" WHERE $timeFilter AND  (\"ssh_type\" = 'SERVER') GROUP BY time(1s), \"COMMAND\") GROUP BY time($interval), \"COMMAND\"  fill(none)",
     "select": [
      [
       { "params": [ "%CPU" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "COMMAND", "operator": "!=", "value": "mongodump" }
     ]
    }
   ]
  },
  {
   "title": "Server Process RAM Usage",
   "type": "bargauge",
   "description": "95% percentille of last 24h",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" }
     ],
     "measurement": "processStats",
     "query": "SELECT PERCENTILE( *, 90) FROM (SELECT sum(\"%MEM\") FROM \"$SPP_Server\".\"rp_days_14\".\"processStats\" WHERE $timeFilter AND  (\"ssh_type\" = 'SERVER')  GROUP BY time(1s), \"COMMAND\") GROUP BY time($interval), \"COMMAND\"  fill(none)",
     "select": [
      [
       { "params": [ "%MEM" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "COMMAND", "operator": "!=", "value": "mongodump" }
     ]
    }
   ]
  },
  {
   "title": "Additional Statistics (Total of last 24h)",
   "type": "stat",
   "description": "Sum of replicated bytes (VM) within the last 24h\nSum of transferred bytes (VM) within the last 24h\nSum of transferred bytes (Office365) within the last 24h",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "VM Replicated",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "vmReplicateStats",
     "select": [
      [
       { "params": [ "replicatedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "VM Backuped",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "Office365 Transferred",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "office365TransfBytes",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "spp_version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Logs Stored 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Catalog Backup",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "jobLogsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}