{
 "title": "SPPMON for IBM Spectrum Protect Plus tulipa_new",
 "description": "Detailed overview with alerts for a single SPP-Server",
 "time": { "from": "now-14d", "to": "now-5m" },
 "panels": [
  { "title": "Spectrum Protect Plus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU Usage",
   "type": "gauge",
   "description": "95% Percentille over last 24h ",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Server RAM Usage",
   "type": "gauge",
   "description": "95% Percentille over last 24h ",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Catalog Space",
   "type": "bargauge",
   "description": "95% Percentille / last 24h of each component memory usage\nMax root storage usage  / last 24h of Server and vSnap",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "percentUsed" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "\"$tag_Mounted\" on $tag_ssh_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "Mounted" ], "type": "tag" }
     ],
     "measurement": "df_ssh",
     "select": [
      [
       { "params": [ "Use%" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" },
      { "condition": "OR", "key": "ssh_type", "operator": "=", "value": "VSNAP" }
     ]
    }
   ]
  },
  {
   "title": "Housekeeping-Job Durations",
   "type": "stat",
   "description": "Duration of the last execution of selected jobs",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Storage Server Inventory" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "CPU / RAM SPP-Server (REST)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "RAM-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Maintenance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Last Hypervisor Inventory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "Last Catalog Backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/.*catalog.*/" },
      { "condition": "AND", "key": "status", "operator": "=", "value": "COMPLETED" },
      { "condition": "AND", "key": "subPolicyType", "operator": "=", "value": "BACKUP" }
     ]
    }
   ]
  },
  {
   "title": "Last Storage Server Inventory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "end" ], "type": "field" },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Storage Server Inventory" }
     ]
    }
   ]
  },
  {
   "title": "Highest CPU load by Component",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ssh_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT max(\"%idle\") *-1 + 100 FROM \"ssh_mpstat_cmd\" WHERE $timeFilter GROUP BY time(10m), \"COMMAND\"",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "SPP Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 12, "y": 12 } },
  {
   "title": "SPPmon Collection Errors (24h)",
   "type": "gauge",
   "description": "This panel shows how much the dela did increase, leaving out going down again.\nGood for noticing errors, even if they disappeared",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "--constant",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM \"sppmon_metrics\" WHERE $timeFilter AND (\"constant\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--hourly",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM \"sppmon_metrics\" WHERE $timeFilter AND (\"hourly\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--daily",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM \"sppmon_metrics\" WHERE $timeFilter AND (\"daily\" = 'True'))  GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--all",
     "measurement": "sppmon_metrics",
     "query": "SELECT sum(*) FROM (SELECT non_negative_difference(\"errorCount\") FROM \"sppmon_metrics\" WHERE  $timeFilter AND (\"all\" = 'True')) GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Catalog Backup Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Catalog Backup",
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/.*catalog.*/" }
     ]
    }
   ]
  },
  {
   "title": "SPP CPU Usage (by process)",
   "type": "bargauge",
   "description": "90% percentille of last 24h per Commandgroup",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" }
     ],
     "measurement": "processStats",
     "query": "SELECT PERCENTILE( *, 90) FROM (SELECT sum(\"%CPU\") FROM \"rp_days_14\".\"processStats\" WHERE $timeFilter AND  (\"ssh_type\" = 'SERVER')  GROUP BY time(1s), \"COMMAND\") GROUP BY time($interval), \"COMMAND\"  ",
     "select": [
      [
       { "params": [ "%CPU" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "COMMAND", "operator": "!=", "value": "mongodump" }
     ]
    }
   ]
  },
  {
   "title": "SPP RAM Usage (by process)",
   "type": "bargauge",
   "description": "90% percentille of last 24h",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" }
     ],
     "measurement": "processStats",
     "query": "SELECT PERCENTILE( *, 90) FROM (SELECT sum(\"%MEM\") FROM \"rp_days_14\".\"processStats\" WHERE $timeFilter AND  (\"ssh_type\" = 'SERVER')  GROUP BY time(1s), \"COMMAND\") GROUP BY time($interval), \"COMMAND\"  ",
     "select": [
      [
       { "params": [ "%MEM" ], "type": "field" },
       { "params": [ "90" ], "type": "percentile" }
      ]
     ],
     "tags": [
      { "key": "COMMAND", "operator": "!=", "value": "mongodump" }
     ]
    }
   ]
  },
  {
   "title": "VM Statistics (Last 24h)",
   "type": "stat",
   "description": "Sum of replicated bytes within the last 24h\nSum of transferred bytes within the last 24h\n",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Amount Replicated",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "vmReplicateStats",
     "select": [
      [
       { "params": [ "replicatedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA0398" }
     ]
    },
    {
     "alias": "Amount Protected",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "SPP Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "spp_version" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Logs Stored 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "jobLogsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SPP Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU / RAM SPP-Server (REST)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "RAM-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "query": "SELECT mean(\"memoryUtil\") *100 FROM \"cpuram\" WHERE (\"time\" < 1596461046000) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "CPU-Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes CPU Usage (sshcmd: top)",
   "type": "graph",
   "description": "Selected Processes monitored by top command\n\"java\", \"mongo\", \"beam.smp\".\nQuerie calcualted due an inner querie to filter out the PID. Simple \"mean\" would result in a falsly low result",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT sum(*) FROM (SELECT mean(\"%CPU\") FROM \"rp_days_14\".\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time($interval), \"COMMAND\", \"PID\" fill(none)) GROUP BY  \"COMMAND\", time($interval) FILL(none)",
     "select": [
      [
       { "params": [ "%CPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" }
     ]
    }
   ]
  },
  {
   "title": "Component CPU (sshcmd: MP-ssh)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ssh_type $tag_hostName",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1 + 100 FROM \"server_mpstat\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "%idle", "operator": "<", "value": "99.5" }
     ]
    }
   ]
  },
  {
   "title": "RAM by Component Used (sshcmd: free)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hostName $tag_ssh_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "query": "SELECT mean(\"used\")  / mean(total) FROM \"ssh_free_cmd\" WHERE (\"name\" = 'Mem') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"ssh_type\" fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / mean(total)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes RAM Usage (sshcmd: top)",
   "type": "graph",
   "description": "Mean-Sum of process-group displayed",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT sum(*) FROM (SELECT mean(\"%MEM\") FROM \"rp_days_14\".\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time($interval), \"COMMAND\", \"PID\" fill(none)) GROUP BY  \"COMMAND\", time($interval) FILL(none)",
     "select": [
      [
       { "params": [ "%MEM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" }
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes RAM Usage (sshcmd: top)",
   "type": "graph",
   "description": "Selected Processes monitored by top command\n\"java\", \"mongo\", \"beam.smp\"",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT sum(*) FROM (SELECT mean(\"MEM_ABS\") FROM \"rp_days_14\".\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time($interval), \"COMMAND\", \"PID\" fill(none)) GROUP BY  \"COMMAND\", time($interval) FILL(none)",
     "select": [
      [
       { "params": [ "MEM_ABS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP-Server File System",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "percentUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Usage (Server & vSnap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ssh_type: $tag_hostName on \"$tag_Mounted\"",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "Mounted" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "df_ssh",
     "select": [
      [
       { "params": [ "Use%" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" },
      { "condition": "OR", "key": "ssh_type", "operator": "=", "value": "VSNAP" }
     ]
    }
   ]
  },
  {
   "title": "Deduplication / Compression VSNAP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Compression Ratio $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsnap_pools",
     "query": "SELECT \"size_free\" FROM \"vsnap_pools\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "compression_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Deduplication Ratio $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsnap_pools",
     "query": "SELECT \"size_free\" FROM \"vsnap_pools\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "deduplication_ratio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Protection Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "All Job Durations",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_jobName]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Catalog Backup Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/catalog/" },
      { "condition": "AND", "key": "subPolicyType", "operator": "=", "value": "BACKUP" }
     ]
    }
   ]
  },
  {
   "title": "Maintenance Job Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT mean(\"duration\")  / 1000 FROM \"jobs\" WHERE (\"jobName\" = 'Maintenance') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Inventory Job Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 53 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "Application Inventory Job Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Application Server Inventory" }
     ]
    }
   ]
  },
  {
   "title": "VMware Protection Job Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_subPolicyType $tag_jobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subPolicyType" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/vmware.*/" }
     ]
    }
   ]
  },
  {
   "title": "DB2 Protection Job Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/db2.*/" }
     ]
    }
   ]
  },
  {
   "title": "Office365 Job Durations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_subPolicyType $tag_jobName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "subPolicyType" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/office365/" }
     ]
    }
   ]
  },
  { "title": "Additional Job Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "SuccessRatio by resource type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName $tag_resourceType sucess ratio",
     "groupBy": [
      { "params": [ "resourceType" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs_statistics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       { "params": [ "*100 / total" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unsuccessful jobs overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 73 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "jobId" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT first(\"percent\") AS \"Last Percent\", first(\"numTasks\") AS \"Last numTasks\", first(\"duration\") AS \"Last Duration\", count(\"duration\") AS \"Times of Failure / 14 Days\" FROM \"rp_days_90\".\"jobs\" WHERE (\"status\" != 'COMPLETED') AND $timeFilter GROUP BY \"status\", \"jobName\", \"jobId\"",
     "select": [
      [
       { "params": [ "start" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" },
       { "params": [ "Last Failed" ], "type": "alias" }
      ],
      [
       { "params": [ "numTasks" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last numTasks" ], "type": "alias" }
      ],
      [
       { "params": [ "percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last Percent" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Last Duration" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Times of Failure / 14 Days" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "COMPLETED" }
     ]
    }
   ]
  },
  {
   "title": "Total count by ResourceType",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 81 },
   "targets": [
    {
     "alias": "$tag_jobName $tag_resourceType total count",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "resourceType" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "jobs_statistics",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "resourceType", "operator": "!=", "value": "database" }
     ]
    }
   ]
  },
  {
   "title": "List of unsucessfull jobs",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 81 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "jobId" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "percent" ], "type": "field" },
       { "params": [ "Percent" ], "type": "alias" }
      ],
      [
       { "params": [ "num" ], "type": "field" },
       { "params": [ "numTasks" ], "type": "alias" }
      ],
      [
       { "params": [ "duration" ], "type": "field" },
       { "params": [ "Duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "COMPLETED" }
     ]
    }
   ]
  },
  {
   "title": "Jobs status overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_status Count",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed Jobs status overview",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName $tag_status Count",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "!=", "value": "COMPLETED" }
     ]
    }
   ]
  },
  {
   "title": "VM Backup Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName total count",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs_statistics",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "resourceType", "operator": "=", "value": "vm" }
     ]
    },
    {
     "alias": "$tag_jobName sucess ratio",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs_statistics",
     "select": [
      [
       { "params": [ "success" ], "type": "field" },
       { "params": [ "*100 / total" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "resourceType", "operator": "=", "value": "vm" }
     ]
    }
   ]
  },
  { "title": "VMware & Hyper-V Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Virtual Machine Protection Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "VM Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "VM Protected: $tag_isProtected",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "isProtected" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "cpu" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of VMs per SLA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_slaName]]",
     "groupBy": [
      { "params": [ "slaName" ], "type": "tag" }
     ],
     "measurement": "slaStats",
     "query": "SELECT \"vmCountBySLA\" AS $tag_slaName FROM \"slaStats\" WHERE $timeFilter GROUP BY \"slaName\"",
     "select": [
      [
       { "params": [ "vmCountBySLA" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vmCountBySLA", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Size (from hypervisor inventory)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "VM avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "commited" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "VM smallest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "query": "SELECT min(\"commited\") FROM \"vms\" WHERE (\"commited\" != 0) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "commited" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "commited", "operator": "!=", "value": "0" }
     ]
    },
    {
     "alias": "VM largest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "commited" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "VM 5% Percitille",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "commited" ], "type": "field" },
       { "params": [ "5" ], "type": "percentile" }
      ]
     ]
    },
    {
     "alias": "VM 95% Percitille",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vms",
     "select": [
      [
       { "params": [ "commited" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Backup Sucess Rate (virtual disks)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "VM Failures",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT count(\"TotalVMDKs\") -sum(protectedVMDKs) FROM \"rp_days_14\".\"vmBackupSummary\" WHERE (\"status\" = 'failed' AND \"messageId\" = 'CTGGA2384') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "TotalVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "-sum(protectedVMDKs)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "failed" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "Sucess Ratio",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT sum(\"protectedVMDKs\") / sum(TotalVMDKs) FROM \"rp_days_14\".\"vmBackupSummary\" WHERE (\"status\" = 'complete' OR \"status\" = 'partial' OR \"status\" = 'failed' AND \"messageId\" = 'CTGGA2384') AND $timeFilter GROUP BY time(24h) fill(none)",
     "select": [
      [
       { "params": [ "protectedVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ sum(TotalVMDKs)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "partial" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "failed" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "VM Success",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT \"TotalVMDKs\" - protectedVMDKs FROM \"vmBackupSummary\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "protectedVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "Mixture of Hyper-V and VMware",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 114 },
   "targets": [
    {
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountHyperV" ], "type": "field" }
      ],
      [
       { "params": [ "vmCountVMware" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Total Data Protected",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Backed up bytes",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "partial" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "Replicated bytes",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmReplicateStats",
     "select": [
      [
       { "params": [ "replicatedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA0398" }
     ]
    }
   ]
  },
  {
   "title": "By Proxy: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "partial" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By VSnap: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 129 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_vsnaps",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "vsnaps" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Type: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 129 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Type: $tag_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "OR", "key": "status", "operator": "=", "value": "partial" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Proxy: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By VSnap: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 136 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vsnaps",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "vsnaps" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Type: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 136 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  { "title": "vSnap Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Site Storage Used (by percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_siteName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "siteName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "pct_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Site Storage Used (by capacity)",
   "type": "graph",
   "description": "Selects mean of each unique storage, sums up to total per site",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_siteName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "siteName" ], "type": "tag" },
      { "params": [ "storageId" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "storages",
     "query": "SELECT sum(used_mean) FROM (SELECT mean(\"used\") AS \"used_mean\" FROM \"rp_days_14\".\"storages\" WHERE $timeFilter GROUP BY time($__interval), \"siteName\", \"storageId\") GROUP BY  time($__interval), \"siteName\" fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_mean" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vSnap Storage Used (by percent)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_hostAddress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostAddress" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "pct_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vSnap Storage Used (by capacity)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostAddress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostAddress" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "vSnap ARC Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsnap_system_stats",
     "select": [
      [
       { "params": [ "size_arc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VSnap CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 158 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VSNAP" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VSNAP" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "VADP Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "VADP Proxy State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "vadpName" ], "type": "tag" }
     ],
     "measurement": "vadps",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "State" ], "type": "alias" }
      ],
      [
       { "params": [ "siteName" ], "type": "field" },
       { "params": [ "Site" ], "type": "alias" }
      ],
      [
       { "params": [ "version" ], "type": "field" },
       { "params": [ "Version" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VADP Proxy State per Site",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_siteName Enabled",
     "groupBy": [
      { "params": [ "siteName" ], "type": "tag" }
     ],
     "measurement": "vadps",
     "select": [
      [
       { "params": [ "enabled_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VADP CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VADP" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VADP" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "Cloud Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "Cloudproxy CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $tag_name on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "CLOUDPROXY" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "CLOUDPROXY" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "Alerts & State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 189 } },
  {
   "title": "SPPmon Collection Error delta Display",
   "type": "gauge",
   "description": "Displays the final change rate of errors which occured, going to stay at 0 if all is on a normal \"error\"-level",
   "gridPos": { "h": 16, "w": 5, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 108 }
   ]
  },
  {
   "title": "SPPmon Collection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 190 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Constant Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Daily Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "All Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Hourly Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Other Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  { "title": "SPP active Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 14, "y": 190 } },
  { "title": "SPP Alert History", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 190 } },
  {
   "title": "SPPmon Collection Errors delta",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 5, "y": 198 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "--daily",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--all",
     "measurement": "sppmon_metrics",
     "query": "SELECT non_negative_difference(difference(\"errorCount\")) FROM \"sppmon_metrics\" WHERE (\"all\" = 'True') AND $timeFilter",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--constant",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--hourly",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Others",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Constant Error Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 206 },
   "targets": [
    {
     "alias": "Test",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "errorMessages" ], "type": "field" },
       { "params": [ "Error Messages" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Hourly Error Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 206 },
   "targets": [
    {
     "alias": "Test",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "errorMessages" ], "type": "field" },
       { "params": [ "Error Messages" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Other Error Messages",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 206 },
   "targets": [
    {
     "alias": "Test",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "errorMessages" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "constant", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "InfluxDB version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 214 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "sppmon_metrics",
     "query": "show diagnostics",
     "select": [
      [
       { "params": [ "version" ], "type": "field" }
      ],
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP & SPPMon version",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 214 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "spp_build" ], "type": "tag" },
      { "params": [ "spp_version" ], "type": "tag" },
      { "params": [ "sppmon_version" ], "type": "tag" }
     ],
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SPPMon Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 220 } },
  {
   "title": "SPPMON Runtime Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 221 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "daily",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "All",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "constant",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Everything Max(12h)",
     "groupBy": [
      { "params": [ "12h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Everything not listed",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    },
    {
     "alias": "hourly",
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 230 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Table: [[tag_tableName]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tableName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\") FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(30m), \"tableName\"",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Duration per Item",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 230 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Avg Duration(ns) per Item",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\")  / (mean(item_count)/1000) FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(10s), \"tableName\"",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / mean(item_count)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avgerage Query Item Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 230 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Table: [[tag_tableName]]",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "tableName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\") FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(30m), \"tableName\"",
     "select": [
      [
       { "params": [ "item_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}