{
 "title": "SPPMON Long Term View (90 Days / Infinite)",
 "description": "Long Term overview with variables but no alerts",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "SPP_Server", "label": "Server to be shown", "query": "influxdb" },
   { "name": "rp", "label": "Time Range", "query": "rp_days_90,rp_inf" }
  ]
 },
 "panels": [
  { "title": "Spectrum Protect Plus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU / RAM SPP-Server (REST)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU-Usage",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "RAM-Usage",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Server Catalog Space Used",
   "type": "graph",
   "description": "max 90% Percentille  of each component memory usage",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "percentUsed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Housekeeping-Job Durations",
   "type": "graph",
   "description": "Duration selected jobs",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Storage Server Inventory" },
      { "condition": "OR", "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "VM Protection Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Protected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountProtected" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Unprotected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountUnprotected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Highest CPU load by Component",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ssh_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT max(\"%idle\") *-1 + 100 FROM \"ssh_mpstat_cmd\" WHERE $timeFilter GROUP BY time(10m), \"COMMAND\"",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Catalog Backup Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Catalog Backup",
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/.*catalog.*/" }
     ]
    }
   ]
  },
  {
   "title": "VM Statistics ",
   "type": "graph",
   "description": "Sum of replicated bytes \nSum of transferred bytes\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Replicated Bytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmReplicateStats",
     "select": [
      [
       { "params": [ "replicatedBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA0398" }
     ]
    },
    {
     "alias": "Backuped Bytes",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "sum_transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "Highest RAM load by Component",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_ssh_type",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "ssh_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "query": "SELECT max(\"%idle\") *-1 + 100 FROM \"ssh_mpstat_cmd\" WHERE $timeFilter GROUP BY time(10m), \"COMMAND\"",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / total" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Logs Stored",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "jobs",
     "select": [
      [
       { "params": [ "jobLogsCount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts & State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "SPPmon Collection Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Constant Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Daily Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "All Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Hourly Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Other Errors",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "SPP & SPPMon version",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "spp_build" ], "type": "tag" },
      { "params": [ "spp_version" ], "type": "tag" },
      { "params": [ "sppmon_version" ], "type": "tag" }
     ],
     "measurement": "sppmon_metrics",
     "query": "SELECT last(\"duration\"), \"version\" FROM \"rp_days_14\".\"sppmon_metrics\" WHERE $timeFilter GROUP BY \"version\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPPmon Collection Errors delta",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "--daily",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--all",
     "measurement": "sppmon_metrics",
     "query": "SELECT non_negative_difference(difference(\"errorCount\")) FROM \"sppmon_metrics\" WHERE (\"all\" = 'True') AND $timeFilter",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--constant",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "--hourly",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Others",
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "sum_errorCount" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    }
   ]
  },
  { "title": "SPP Server Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "CPU / RAM SPP-Server (REST)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "RAM-Usage",
     "measurement": "cpuram",
     "query": "SELECT mean(\"memoryUtil\") *100 FROM \"cpuram\" WHERE (\"time\" < 1596461046000) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "memoryUtil" ], "type": "field" },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "CPU-Usage",
     "measurement": "cpuram",
     "select": [
      [
       { "params": [ "cpuUtil" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes CPU Usage (sshcmd: top)",
   "type": "graph",
   "description": "Selected Processes monitored by top command\n\"java\", \"mongo\", \"beam.smp\"",
   "gridPos": { "h": 14, "w": 11, "x": 13, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT * FROM (SELECT sum(\"%CPU\") FROM $rp.\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time(1s), \"COMMAND\") GROUP BY  \"COMMAND\"  ",
     "select": [
      [
       { "params": [ "mean_%CPU" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" }
     ]
    }
   ]
  },
  {
   "title": "Component CPU (sshcmd: MP-ssh)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_ssh_type $tag_hostName",
     "groupBy": [
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "ssh_type" ], "type": "tag" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1 + 100 FROM \"server_mpstat\" WHERE $timeFilter GROUP BY time($__interval), \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       { "params": [ "*-1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "mean_%idle", "operator": "<", "value": "99.5" }
     ]
    }
   ]
  },
  {
   "title": "RAM by Component Used (sshcmd: free)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 6, "x": 7, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hostName $tag_ssh_type",
     "groupBy": [
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "ssh_type" ], "type": "tag" }
     ],
     "measurement": "ssh_free_cmd",
     "query": "SELECT mean(\"used\")  / mean(total) FROM \"ssh_free_cmd\" WHERE (\"name\" = 'Mem') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"ssh_type\" fill(none)",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       { "params": [ " / total" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes RAM Usage (sshcmd: top)",
   "type": "graph",
   "description": "Mean-Sum of process-group displayed",
   "gridPos": { "h": 15, "w": 7, "x": 13, "y": 59 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT * FROM (SELECT sum(\"%MEM\") FROM \"$rp\".\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time(1s), \"COMMAND\") GROUP BY \"COMMAND\" ",
     "select": [
      [
       { "params": [ "mean_%MEM" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "SERVER" }
     ]
    }
   ]
  },
  {
   "title": "SPP-Server Processes RAM Usage (sshcmd: top)",
   "type": "graph",
   "description": "Selected Processes monitored by top command\n\"java\", \"mongo\", \"beam.smp\"",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_COMMAND",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "COMMAND" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "processStats",
     "query": "SELECT * FROM (SELECT sum(\"MEM_ABS\") FROM \"$rp\".\"processStats\" WHERE (\"ssh_type\" = 'SERVER') AND $timeFilter GROUP BY time(1s), \"COMMAND\") GROUP BY  \"COMMAND\"  ",
     "select": [
      [
       { "params": [ "mean_MEM_ABS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SPP Server Catalog Space Used",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "sppcatalog",
     "select": [
      [
       { "params": [ "percentUsed" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Deduplication / Compression VSNAP",
   "type": "graph",
   "gridPos": { "h": 14, "w": 10, "x": 10, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Compression Ratio $tag_hostName",
     "groupBy": [
      { "params": [ "hostName" ], "type": "tag" }
     ],
     "measurement": "vsnap_pools",
     "query": "SELECT \"size_free\" FROM \"vsnap_pools\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "compression_ratio" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Deduplication Ratio $tag_hostName",
     "groupBy": [
      { "params": [ "hostName" ], "type": "tag" }
     ],
     "measurement": "vsnap_pools",
     "query": "SELECT \"size_free\" FROM \"vsnap_pools\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "deduplication_ratio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Protection Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "All Job Durations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[[tag_jobName]]",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Maintenance Job Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "measurement": "jobs",
     "query": "SELECT mean(\"duration\")  / 1000 FROM \"jobs\" WHERE (\"jobName\" = 'Maintenance') AND $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Maintenance" }
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Inventory Job Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 89 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Hypervisor Inventory" }
     ]
    }
   ]
  },
  {
   "title": "SPP Catalog Backup Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=~", "value": "/catalog/" }
     ]
    }
   ]
  },
  {
   "title": "VMware Protection Job Durations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_subPolicyType $tag_jobName",
     "groupBy": [
      { "params": [ "subPolicyType" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/vmware.*/" }
     ]
    }
   ]
  },
  {
   "title": "Application Inventory Job Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Duration",
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "jobName", "operator": "=", "value": "Application Server Inventory" }
     ]
    }
   ]
  },
  {
   "title": "DB2 Protection Job Durations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 101 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_jobName",
     "groupBy": [
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/db2.*/" }
     ]
    }
   ]
  },
  {
   "title": "Office365 Job Durations",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_subPolicyType $tag_jobName",
     "groupBy": [
      { "params": [ "subPolicyType" ], "type": "tag" },
      { "params": [ "jobName" ], "type": "tag" }
     ],
     "measurement": "jobs",
     "query": "SELECT \"duration\" FROM \"jobs\" WHERE (\"jobName\" = 'Hypervisor Inventory') AND $timeFilter GROUP BY \"jobName\"",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "protection" },
      { "condition": "AND", "key": "jobName", "operator": "=~", "value": "/office365/" }
     ]
    }
   ]
  },
  { "title": "VM & Hyper-V Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 } },
  {
   "title": "vmStats",
   "type": "graph",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "VM total",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCount" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "VM Protected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountProtected" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "VM Unprotected",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountUnprotected" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "number of VMs per SLA",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 9, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_slaName]]",
     "groupBy": [
      { "params": [ "slaName" ], "type": "tag" }
     ],
     "measurement": "slaStats",
     "query": "SELECT \"vmCountBySLA\" AS $tag_slaName FROM \"slaStats\" WHERE $timeFilter GROUP BY \"slaName\"",
     "select": [
      [
       { "params": [ "vmCountBySLA" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "vmCountBySLA", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Hyper-V vs VMware",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmCountHyperV" ], "type": "field" }
      ],
      [
       { "params": [ "vmCountVMware" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Sizes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "alias": "VM avg",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmAvgSize" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "VM smallest",
     "measurement": "vmStats",
     "query": "SELECT min(\"commited\") FROM \"vms\" WHERE (\"commited\" != 0) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "vmMinSize" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "VM largest",
     "measurement": "vmStats",
     "select": [
      [
       { "params": [ "vmMaxSize" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM's Backup Sucess rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 137 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Failure Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT \"TotalVMDKs\" - protectedVMDKs FROM \"vmBackupSummary\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "sum_TotalVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "- sum(sum_protectedVMDKs)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "failed" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "Sucess Ratio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT sum(\"protectedVMDKs\") / sum(TotalVMDKs) FROM \"vmBackupSummary\" WHERE $timeFilter GROUP BY time(24h) fill(none)",
     "select": [
      [
       { "params": [ "sum_protectedVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/ sum(sum_TotalVMDKs)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    },
    {
     "alias": "Total Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "query": "SELECT \"TotalVMDKs\" - protectedVMDKs FROM \"vmBackupSummary\" WHERE $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "sum_TotalVMDKs" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Proxy: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "sum_transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By VSnap: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 147 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_vsnaps",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "vsnaps" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "sum_transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Type: VM Backup Transferred Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 147 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "Type: $tag_type",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "sum_transferredBytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Proxy: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 155 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By VSnap: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 155 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_vsnaps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vsnaps" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  {
   "title": "By Type: VM Backup Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 155 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "vmBackupSummary",
     "select": [
      [
       { "params": [ "throughputBytes/s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "complete" },
      { "condition": "AND", "key": "messageId", "operator": "=", "value": "CTGGA2384" }
     ]
    }
   ]
  },
  { "title": "vSnap Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "vSnap storage space utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "pct_used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vSnap storage space utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "[[tag_name]]",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "storages",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vsnap ARC Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vsnap_system_stats",
     "select": [
      [
       { "params": [ "size_arc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VSnap CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $tag_name on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VSNAP" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(mean_total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VSNAP" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "VADP Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 180 } },
  {
   "title": "VADP Proxy State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_siteName Enabled",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "siteName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vadps",
     "query": "SELECT count(\"state\") FROM \"rp_half_year\".\"vadps\" WHERE (\"state\" =~ /ENABLED/) AND $timeFilter GROUP BY time($interval), \"siteName\"",
     "select": [
      [
       { "params": [ "enabled_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [
         " / (sum(enabled_count)+sum(disabled_count))"
        ],
        "type": "math"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VADP Proxy State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 181 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_siteName Enabled Count",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "siteName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "vadps",
     "query": "SELECT count(\"state\") FROM \"rp_half_year\".\"vadps\" WHERE (\"state\" =~ /ENABLED/) AND $timeFilter GROUP BY time($interval), \"siteName\"",
     "select": [
      [
       { "params": [ "enabled_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VADP CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $tag_name on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VADP" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "VADP" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "Cloud Proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Cloudproxy CPU & RAM Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 198 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $tag_name on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_mpstat_cmd",
     "query": "SELECT mean(\"%idle\") *-1+100 FROM \"ssh_mpstat_cmd\" WHERE (\"ssh_type\" = 'VADP') AND $timeFilter GROUP BY time($__interval), \"hostName\", \"host\" fill(none)",
     "select": [
      [
       { "params": [ "%idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1+100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "CLOUDPROXY" }
     ]
    },
    {
     "alias": "RAM on host $tag_hostName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ssh_free_cmd",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/mean(total) " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ssh_type", "operator": "=", "value": "CLOUDPROXY" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "Mem" }
     ]
    }
   ]
  },
  { "title": "SPPMon Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 } },
  {
   "title": "SPPMON Runtime Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 207 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "daily",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "daily", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "All",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "constant",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "constant", "operator": "=", "value": "True" }
     ]
    },
    {
     "alias": "Everything Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Everything not listed",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "query": "SELECT mean(\"duration\") FROM \"sppmon_metrics\" WHERE $timeFilter GROUP BY time(12h)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "all", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "constant", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "daily", "operator": "!=", "value": "True" },
      { "condition": "AND", "key": "hourly", "operator": "!=", "value": "True" }
     ]
    },
    {
     "alias": "hourly",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sppmon_metrics",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hourly", "operator": "=", "value": "True" }
     ]
    }
   ]
  },
  {
   "title": "Average Query Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "alias": "Table: [[tag_tableName]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tableName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\") FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(30m), \"tableName\"",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Query Duration per Item",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 216 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Avg Duration(ns) per Item",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\")  / (mean(item_count)/1000) FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(10s), \"tableName\"",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / mean(item_count)" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avgerage Query Item Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Table: [[tag_tableName]]",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "tableName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "influx_metrics",
     "query": "SELECT mean(\"duration_ms\") FROM \"influx_metrics\" WHERE $timeFilter GROUP BY time(30m), \"tableName\"",
     "select": [
      [
       { "params": [ "item_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}